Add User table to postgresql db.
infinityworks/snailx_api pull request #40
Opened 2018-10-17 15:16 UTC by sorsby

- Create User table, need to run make migrate-db upgrade-db to get the new database schema working.
- Added methods to User model.
- Add tests for create_user command.

2018-10-17 16:27 UTC, MikeSilverstone requested changes

2018-10-17 16:40 UTC, sorsby commented on api/commands/create_user_command.py
> +        password = prompt_pass(
What does this mean? prompt_pass hides the password as you type it.

2018-10-17 16:43 UTC, sorsby commented on api/test_runner.py
>  # runner = unittest.TextTestRunner(verbosity=3)
??????

2018-10-17 16:46 UTC, glossopm requested changes

2018-10-17 16:46 UTC, glossopm commented on api/tests/test_command_create_user.py
> +from unittest.mock import MagicMock, Mock
Mock isn't used?

2018-10-17 16:47 UTC, sorsby commented on api/manage.py
> +from flask_bcrypt import Bcrypt
yeet

2018-10-17 16:47 UTC, sorsby commented on api/tests/test_command_create_user.py
> +from unittest.mock import MagicMock, Mock
yeet

2018-10-18 07:38 UTC, MikeSilverstone commented on api/test_runner.py
>  # runner = unittest.TextTestRunner(verbosity=3)
'#runner = unittest.TextTestRunner(verosity=3)'

is just a commented out line of code, does it need to be there?

2018-10-18 07:39 UTC, MikeSilverstone commented on api/commands/create_user_command.py
> +        password = prompt_pass(
Cool. 👍

2018-10-18 12:48 UTC, glossopm approved these changes

2018-10-18 14:11 UTC, sorsby commented on api/tests/test_command_create_user.py
> +        expected_user = User(username='test', email='test', password='test')
I added another test to check the password hashing, have a look see.

2018-10-18 14:12 UTC, sorsby commented on api/commands/create_user_command.py
> +        username = prompt(
Self sabotage? depends who is using the commands and also it wasn't on the card.
This is essentially just hardcoding the users and doing it directly in the db wouldn't have any validation either.

2018-10-19 08:57 UTC, MikeSilverstone approved these changes

2018-10-19 08:58 UTC, merged